# Generated by Django 2.0.6 on 2018-06-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codedjob',
            name='total_words',
            field=models.IntegerField(default=1),
        ),
    ]
