# Generated by Django 2.0.6 on 2018-06-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_codedjob_total_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='codedjob',
            name='total_fem_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codedjob',
            name='total_masc_words',
            field=models.IntegerField(default=0),
        ),
    ]
