# Generated by Django 2.0.6 on 2018-06-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180616_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='codedjob',
            name='fem_word_proportion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='codedjob',
            name='masc_word_proportion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
