# Generated by Django 2.0.6 on 2018-06-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20180616_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codedjob',
            name='fem_word_proportion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='codedjob',
            name='masc_word_proportion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
