# Generated by Django 2.0.6 on 2018-06-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_codedjob_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='codedjob',
            name='gender_words',
            field=models.TextField(default=''),
        ),
    ]
