# Generated by Django 2.0.6 on 2018-07-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20180617_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='codedjob',
            name='unique_id',
            field=models.IntegerField(default=0),
        ),
    ]
