# Generated by Django 2.0.6 on 2018-07-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_codedjob_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codedjob',
            name='unique_id',
        ),
    ]
