mascwords = [
    'active',
    'adventurous',
    'aggress',
    'ambitio',
    'analy',
    'assert',
    'athlet',
    'autonom',
    'boast',
    'challeng',
    'compet',
    'confident',
    'courag',
    'decide',
    'decisive',
    'decision',
    'determin',
    'domina',
    'force',
    'greedy',
    'guy',
    'head-strong',
    'headstrong',
    'hierarch',
    'hostil',
    'impulsive',
    'intens',
    'independen',
    'individual',
    'intellect',
    'lead',
    'logic',
    'masculine',
    'objective',
    'opinion',
    'outspoken',
    'persist',
    'principle',
    'reckless',
    'self-confiden',
    'selfconfiden',
    'self-relian',
    'selfrelian',
    'self-sufficien',
    'selfsufficien',
    'stubborn',
    'superior',
    'beer',
    'brogrammer',
    'businessm',
    'chairman',
    'enforce',
    'exhaustive',
    'fast-paced',
    'fearless',
    'flawless',
    'foosball',
    'guru',
    'hacker',
    'high-performance',
    'jedi',
    'man-hours',
    'man-made',
    'manmade',
    'mankind',
    'mission-critical',
    'ninja',
    'rigid',
    'rockstar',
    'strong',
    'superstar',
    'wizard',
    'workforce',
]

femwords = [
    'affectionate',
    'child',
    'cheer',
    'commit',
    'communal',
    'compassion',
    'connect',
    'considerate',
    'cooperat',
    'co-operat',
    'depend',
    'emotiona',
    'empath',
    'female',
    'feminine',
    'flatterable',
    'gentle',
    'honest',
    'interdependen',
    'inter-dependen',
    'interpersona',
    'inter-persona',
    'kind',
    'kinship',
    'loyal',
    'modesty',
    'nag',
    'nurtur',
    'pleasant',
    'polite',
    'quiet',
    'respon',
    'sensitiv',
    'submissive',
    'support',
    'sympath',
    'tender',
    'together',
    'trust',
    'understand',
    'warm',
    'whin',
    'woman',
    'women',
    'yield',
]

mascphrases = [
    'best of the best',
    'play hard',
    'set the standard',
    'sets the standard',
    'stock options',
    'stringent expectations',
    'take risks',
    'takes risks',
    'type a',
    'work hard',
    'v.i.p.',
]

femphrases = []

mascexactwords = [
    'manage',
    'man',
    'men',
    'male',
    'males',
    'drive',
    'driving',
    'driven',
]

femexactwords = []
